---
title: "Covid19_Model_calibration"
author: "FG"
date: "9/3/2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r message FALSE, warning=FALSE}
#library (dplyr)
library(deSolve)
library(reshape2)
library(ggplot2)
```

```{r}
CV19_backup<- read.csv("https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv")
```

```{r}
#head(CV19_backup);tail(CV19_backup)
```
```{r}
names(CV19_backup)
```


```{r message = FALSE}
require(dplyr)
```


```{r}

CV19_IT<- CV19_backup%>%select(data, totale_casi, nuovi_positivi, deceduti)
head(CV19_IT)
```

```{r}
length(CV19_IT$data)
```



```{r}
data<- data.frame(time= 1:length(CV19_IT$data), number_infected = CV19_IT$nuovi_positivi[1:length(CV19_IT$data)] )  #real distribution of new infected
head(data)
```

```{r echo = FALSE}

print("Peak prevalence of the epidemic:")
max(data$number_infected)
print("Timing of the peak (days):")
data$time[data$number_infected==max(data$number_infected)]
print("Duration of the epidemic (days):")
max(data$time[data$number_infected>1])-min(data$time[data$number_infected>1])
```




```{r }
##SIR model

#p <- 0.08   #effetto (treatment/vaccination)

N<- sum(CV19_IT$nuovi_positivi)

initial_state_values <- c(S = (1-p)*(N-1),   # Susceptible
                          A = 0,             # Asymptomatic
                          E = 0,             # Exposed
                          I = 1,             # Infected
                          R = p*N)           # Recovered

# Adding the parameters vector
parameters <- c(beta = 0.457,  # infection rate
                beta_t = 0,  # infection rate under treatment 
                gamma = 1/4, # recovery rate
                gamma_t = 0, # recovery rate under treatment
                r = 1/35,    # epidemic proportion of the population
                p_a = 0.1,     # asymptomatic proportion of the population 
                mu = 0, #0.11/365,  # mortality rate
                b = 0, #0.1/365,    # birth rate
                sigma = 0,          # waning rate 
                h =  0)               # treatment rate
                
times <- seq(from = 0, to = length(CV19_IT$data), by = 1)

# MODEL FUNCTION
sir_model <- function(time, state, parameters) {  
  
  with(as.list(c(state, parameters)), {
    
    N <- S+E+A+I+R
    
    lambda <- beta * I/N    # force of infection
    
    # The differential equations
    dS <- -lambda * S - mu * S + b * N 
    
    dE <- lambda * S - r * E
    dA <- (1-p_a) * lambda * S - gamma * A
      
    dI <-  p_a * lambda * S + r * E - gamma * I - mu * I
    dR <- gamma * A + gamma * I - mu * R + b * N   
    
    #dT <- 
  
    # Output
    return(list(c(dS, dE, dA, dI, dR))) 
  })
}


    
# MODEL OUTPUT

output <- as.data.frame(ode(y = initial_state_values, 
                            times = times, 
                            func = sir_model,
                            parms = parameters))

# PLOT OF THE MODEL FIT

ggplot() +
  geom_line(data = output, aes(x = time, y = I)) +        # plot the model prediction of
                                                          # the number infected as a line
  geom_point(data = data, aes(x = time, y = number_infected), 
             colour = "red") +  # overlay the data as red dots
  xlab("Time (days)")+                                              
  ylab("Number of infected people") +                                 
  labs(title = paste("Model fit to the epidemic curve with beta =", parameters["beta"], 
                     "and gamma =", parameters["gamma"]))+
  xlim(100,200)

```




```{r include = FALSE}

output$total_prevalence <- output$I+output$A  # infected individuals = symptomatic + asymptomatic

output1_long <- melt(as.data.frame(output), id = "time")

ggplot(data = output1_long,                                              # specify object containing data to plot
       aes(x = time, y = value, colour = variable, group = variable)) +  # assign columns to axes and groups
  geom_line() +                                                          # represent data as lines
  xlab("Time (days)")+                                                   # add label for x axis
  ylab("Number") +                                                       # add label for y axis
  labs(colour = "Compartment",                                           # add legend title  
       title = "SEAIR model")
```



```{r echo = FALSE}
#sampled popuplation
print("Peak prevalence of the epidemic:")
max(output$I)
print("Timing of the peak (days):")
output$time[output$I==max(output$I)]
print("Duration of the epidemic (days):")
max(output$time[output$I>1])-min(output$time[output$I>1])
```

```{r}
##test for calculating SSQ (Sum of Squared)

# load packages
library(deSolve)
library(ggplot2)
```



```{r}

SIR_fn <- function(time, state, parameters) {
  
  with(as.list(c(state, parameters)), {
    N  <- S+I+R
    
    dS <- -beta*S*I/N
    dI <- beta*S*I/N - gamma*I
    dR <- gamma*I
    
    return(list(c(dS, dI, dR)))
    
  })
  
}
```



```{r}
SIR_SSQ <- function(parameters, dat) {
  
  result <- as.data.frame(ode(  y = initial_state_values,
                                times = times,
                                func = SIR_fn,
                                parms = parameters)
                          )  
  
  
  dat <- na.omit(dat) 
  deltas2 <- (result$I[result$time %in% data$time] - data$I)^2   
  
  SSQ   <- sum(deltas2)
  
  return(SSQ)}
```



```{r}
## real data-----

data<- data.frame(time= 1:length(CV19_IT$data), I = CV19_IT$nuovi_positivi[1:length(CV19_IT$data)] )


initial_state_values <- c(S = sum(I)-1, I = 1, R = 0)

beta_start  <- 1
gamma_start <- 0.5

times <- seq(from = 0, to = length(CV19_IT$data), by = 1)


optimised <- optim(par = c(beta = beta_start,
                           gamma = gamma_start),
                          fn = SIR_SSQ,
                          dat = data)

optimised #have a look at the model output
```


```{r}
round(optimised$par,4)
```


```{r}
opt_mod <- as.data.frame(ode(y = initial_state_values,
                             times = times,
                             func = SIR_fn,
                             parms = optimised$par))



require(ggplot2)

opt_plot <- ggplot()
opt_plot <- opt_plot + geom_point(aes(x = time, y = I)
                                  , colour = "red"
                                  , shape  = "x" 
                                  , data = data)
opt_plot <- opt_plot + geom_line(aes(x = time, y = I)
                                 , colour = "blue"
                                 , data   = opt_mod)
opt_plot



```

I would add more to set stops on calibration by date
